#+title: 2022 Monthly Dedicated
* Oct
Three things I would like to do more in October.
** Deep Work.
So many distractions, mac apps notification, slack messages, phone apps notifications, ads on the website ect.
We all know about the value of deep work. The hard part is not what and why, it's how. How to stay focus.

I'm using pomotodo app (It's a timer app.). I will only focus on one thing during the 30mins interval. Whatever comes along this period, if it's something I need to do, i will just add it as a todo in my omnifocus app.

If it's something like: watch youtube of the latest episode of whichever channel, "ok, maybe 10mins later".
** 5 mins per day, tidy things up, keep them organized.
I'm a bit lazy, and sometimes I just forgot to put them back to where they were after using them.
Just to take a small step, 5 mins per day.
** Do something to make myself laugh everyday.
I want keep something easy and very enjoyable in this list. Recently, I'm following some subscription account on wechat, they post funny memes everyday. Some are very hilarious.
